### PR TITLE
Allow removal of all listeners for a key

### PR DESCRIPTION
**Pull request by nervetattoo**
Allow removal of all listeners for a key by passing null instead of func -> down(keys, null)

### CODE REVIEW

**Comment by marquete** [comment]
Hi there. I love the idea (it was on my to-do list), but I don't think I'm comfortable with _un_-registering things in a method that _registers_ things. How would you feel instead about modifying `Kibo.prototype.unregisterKeys` like this?

``` javascript
    if(Kibo.isArray(registeredKeys[newKeys[i]])) {
      if(func === null)
        delete registeredKeys[newKeys[i]];
      else
        for(j = 0; j < registeredKeys[newKeys[i]].length; j++)
          if(String(registeredKeys[newKeys[i]][j]) === String(func)) {
            registeredKeys[newKeys[i]].splice(j, 1);
            break;
          }
    }
```

And then letting `up` and `down` dispatch calls accordingly:

``` javascript
Kibo.prototype.down = function(keys, func) {
  return func !== null ? this.registerKeys('down', keys, func) : this.unregisterKeys('down', keys, null);
};

Kibo.prototype.up = function(keys, func) {
  return func !== null ? this.registerKeys('up', keys, func) : this.unregisterKeys('up', keys, null);
};
```

Please let me know what you think. Thank you for your feedback!

**Comment by nervetattoo** [comment]
Yeah, I agree thats a better implementation by far.
It should probably only dispatch to `registerKeys` if it is in fact callable.

**Comment by marquete** [comment]
So do you still want to apply the changes we discussed here? Or I could do it myself if you like, but I'd rather give you credit instead. Cheers!

**Comment by nervetattoo** [comment]
Replaced commit with an implementation closer to yours.

**Comment by marquete** [comment]
Merged. Thank you for your contribution. Cheers!

**Pull request merged**
